version: "3.5"
services: 
  go-gin-template-db-service:
    container_name: go-gin-template-db-only
    image: postgres:alpine
    env_file: ./docker/local.env
    volumes:
      - ./docker/database/postgres/data:/var/lib/postgresql/data
      - ./docker/database/postgres/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"
    tty: true
    restart: always
    healthcheck:
      #IMPORTANT! change this if you have changed a local.env
      test: ["CMD-SHELL", "pg_isready -U go-gin-template-usr -d go-gin-template-db"]
      interval: 10s
      timeout: 5s
      retries: 5
  go-gin-template-adminer-service:
    container_name: go-gin-template-adminer-only
    image: adminer
    restart: always
    ports:
      - 8086:8080
    env_file: ./docker/local.env
    links:
      - go-gin-template-db-service
    depends_on:
      - go-gin-template-db-service